package compliance

// Frameworks maps each supported standard to its controls.
var Frameworks = map[Framework][]Control{
	HIPAA: {
		{ID: "164.308(a)(1)", Name: "Security Management Process", Description: "Implement policies and procedures to prevent, detect, contain, and correct security violations."},
		{ID: "164.308(a)(3)", Name: "Workforce Security", Description: "Implement policies and procedures to ensure all workforce members have appropriate access to ePHI."},
		{ID: "164.308(a)(4)", Name: "Information Access Management", Description: "Implement policies for authorizing access to ePHI in accordance with the Privacy Rule."},
		{ID: "164.308(a)(5)", Name: "Security Awareness and Training", Description: "Implement a security awareness and training program for all workforce members."},
		{ID: "164.308(a)(6)", Name: "Security Incident Procedures", Description: "Implement policies and procedures to address security incidents."},
		{ID: "164.308(a)(7)", Name: "Contingency Plan", Description: "Establish policies for responding to emergencies that damage systems containing ePHI."},
		{ID: "164.310(a)(1)", Name: "Facility Access Controls", Description: "Implement policies to limit physical access to electronic information systems."},
		{ID: "164.312(a)(1)", Name: "Access Control", Description: "Implement technical policies to allow only authorized persons access to ePHI."},
		{ID: "164.312(b)", Name: "Audit Controls", Description: "Implement hardware, software, and procedural mechanisms to record and examine activity in systems containing ePHI."},
		{ID: "164.312(e)(1)", Name: "Transmission Security", Description: "Implement technical security measures to guard against unauthorized access to ePHI over networks."},
	},
	SOC2: {
		{ID: "CC1.1", Name: "Control Environment", Description: "Demonstrates commitment to integrity and ethical values throughout the organization."},
		{ID: "CC2.1", Name: "Information and Communication", Description: "Obtains and uses relevant quality information to support internal control functioning."},
		{ID: "CC3.1", Name: "Risk Assessment", Description: "Specifies suitable objectives to enable identification and assessment of risks to achieving those objectives."},
		{ID: "CC4.1", Name: "Monitoring Activities", Description: "Selects, develops, and performs ongoing and separate evaluations of internal controls."},
		{ID: "CC5.1", Name: "Control Activities - Policies", Description: "Selects and develops control activities that contribute to mitigation of risks to acceptable levels."},
		{ID: "CC6.1", Name: "Logical and Physical Access Controls", Description: "Implements logical access security software, infrastructure, and architectures to protect information assets."},
		{ID: "CC6.6", Name: "External Threat Controls", Description: "Implements logical access security measures to protect against threats from sources outside system boundaries."},
		{ID: "CC7.1", Name: "System Operations", Description: "Detects and monitors for new vulnerabilities and manages them through a defined vulnerability management process."},
		{ID: "CC8.1", Name: "Change Management", Description: "Authorizes, designs, develops, acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures."},
		{ID: "CC9.1", Name: "Risk Mitigation", Description: "Identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions."},
	},
	PCIDSS: {
		{ID: "1.1", Name: "Network Security Controls", Description: "Processes and mechanisms for installing and maintaining network security controls are defined and understood."},
		{ID: "2.1", Name: "Secure Configurations", Description: "Processes and mechanisms for applying secure configurations to all system components are defined and understood."},
		{ID: "3.1", Name: "Account Data Protection", Description: "Processes and mechanisms for protecting stored account data are defined and understood."},
		{ID: "4.1", Name: "Transmission Security", Description: "Processes and mechanisms for protecting cardholder data with strong cryptography during transmission over open, public networks."},
		{ID: "5.1", Name: "Malware Protection", Description: "Processes and mechanisms for protecting all systems and networks from malicious software."},
		{ID: "6.1", Name: "Vulnerability Management", Description: "Processes and mechanisms for developing and maintaining secure systems and software."},
		{ID: "7.1", Name: "Access Control", Description: "Processes and mechanisms for restricting access to system components and cardholder data by business need to know."},
		{ID: "8.1", Name: "User Authentication", Description: "Processes and mechanisms for identifying users and authenticating access to system components."},
		{ID: "9.1", Name: "Physical Access Controls", Description: "Processes and mechanisms for restricting physical access to cardholder data."},
		{ID: "10.1", Name: "Logging and Monitoring", Description: "Processes and mechanisms for logging and monitoring all access to system components and cardholder data."},
	},
	ISO27001: {
		{ID: "A.5.1", Name: "Information Security Policies", Description: "Management direction and support for information security in accordance with business requirements and laws."},
		{ID: "A.6.1", Name: "Internal Organization", Description: "Management framework to initiate and control implementation of information security within the organization."},
		{ID: "A.7.1", Name: "Human Resource Security", Description: "Ensure employees understand responsibilities and are suitable for roles prior to employment."},
		{ID: "A.8.1", Name: "Asset Management", Description: "Identify organizational assets and define appropriate protection responsibilities."},
		{ID: "A.9.1", Name: "Access Control Policy", Description: "Limit access to information and information processing facilities."},
		{ID: "A.10.1", Name: "Cryptographic Controls", Description: "Ensure proper and effective use of cryptography to protect confidentiality, authenticity and integrity."},
		{ID: "A.11.1", Name: "Physical and Environmental Security", Description: "Prevent unauthorized physical access, damage and interference to the organization's information and facilities."},
		{ID: "A.12.1", Name: "Operational Security", Description: "Ensure correct and secure operations of information processing facilities."},
		{ID: "A.13.1", Name: "Network Security Management", Description: "Ensure the protection of information in networks and supporting information processing facilities."},
		{ID: "A.16.1", Name: "Incident Management", Description: "Ensure a consistent and effective approach to managing information security incidents."},
	},
	NISTCSF: {
		{ID: "ID.AM-1", Name: "Asset Inventory", Description: "Physical devices and systems within the organization are inventoried."},
		{ID: "ID.RA-1", Name: "Vulnerability Identification", Description: "Asset vulnerabilities are identified and documented."},
		{ID: "PR.AC-1", Name: "Identity Management", Description: "Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices, users and processes."},
		{ID: "PR.DS-1", Name: "Data at Rest Protection", Description: "Data-at-rest is protected."},
		{ID: "PR.IP-1", Name: "Baseline Configuration", Description: "A baseline configuration of information technology/industrial control systems is created and maintained."},
		{ID: "PR.PT-1", Name: "Audit Logging", Description: "Audit/log records are determined, documented, implemented, and reviewed in accordance with policy."},
		{ID: "DE.CM-1", Name: "Network Monitoring", Description: "The network is monitored to detect potential cybersecurity events."},
		{ID: "DE.AE-1", Name: "Baseline Operations", Description: "A baseline of network operations and expected data flows for users and systems is established and managed."},
		{ID: "RS.RP-1", Name: "Response Planning", Description: "Response plan is executed during or after a cybersecurity incident."},
		{ID: "RC.RP-1", Name: "Recovery Planning", Description: "Recovery plan is executed during or after a cybersecurity incident or adverse situation."},
	},
	HITRUST: {
		{ID: "01.a", Name: "Access Control Policy", Description: "An access control policy is established, documented, and reviewed based on business and security requirements."},
		{ID: "01.b", Name: "User Registration", Description: "A formal user registration and de-registration procedure is implemented to enable assignment of access rights."},
		{ID: "01.d", Name: "User Password Management", Description: "The allocation of passwords is controlled through a formal management process."},
		{ID: "06.d", Name: "Data Protection and Privacy", Description: "Data protection and privacy is ensured as required by relevant legislation, regulations, and contractual clauses."},
		{ID: "07.a", Name: "Inventory of Assets", Description: "All assets are clearly identified and an inventory of all important assets drawn up and maintained."},
		{ID: "09.ab", Name: "Monitoring System Use", Description: "Procedures for monitoring use of information processing facilities are established and results reviewed regularly."},
		{ID: "10.a", Name: "Security Requirements Analysis", Description: "Statements of business requirements for new systems or enhancements to existing systems specify security requirements."},
		{ID: "11.a", Name: "Reporting Information Security Events", Description: "Information security events are reported through appropriate management channels as quickly as possible."},
		{ID: "12.a", Name: "Including Information Security in BCM", Description: "A managed process is developed and maintained for business continuity throughout the organization."},
		{ID: "13.a", Name: "Identifying Applicable Legislation", Description: "All relevant statutory, regulatory, and contractual requirements are explicitly identified and kept up to date."},
	},
}
